version: 0.2
phases:
 pre_build:
  commands:
  - echo Entered pre-build phase, nothing to do
 build:
  commands:
  - echo Build started on `date`
  - mvn install
 post_build:
  commands:
  - echo Entered the post-build phase
artifacts:
 files:
  - '**/FrontControllerDemo.war
  - 'appspec.yaml'
  discard-paths: yes