version: 0.2
phases:
 pre_build:
  commands:
  - echo Entered pre-build phase, nothing to do
 build:
  commands:
  - echo "Entering build phase now"
  - mvn clean package
 post_build:
  commands:
   - echo "end of build"
artifacts:
 files:
  - '**/FrontControllerDemo.war'